### ISSUE TITLE
Woot Tartarus chunkgenerator

### ISSUE THREAD

**Issue by zezreli** [Ipsis/Woot#504] opened 2021-02-16 16:40 UTC
Hey, Im playing on minecraft version 1.16.5 with forge version 36.0.26 and a bunch of other mods, and when i tried logging in to my world it started to crash, and the crash logs point towards woot.simulator.tartarus.tartarusChunkGenerator, saying that it as a negative value and that it must have a positive value.

[crash-2021-02-16_17.28.00-server.txt](https://github.com/Ipsis/Woot/files/5990145/crash-2021-02-16_17.28.00-server.txt)

this is the crash file

**Comment by sandalle** [comment] 2021-02-16 22:13
Sometimes I get this crash: [crash-2021-02-16_13.41.22-server.txt](https://github.com/Ipsis/Woot/files/5991852/crash-2021-02-16_13.41.22-server.txt)

Other times I get this crash, which directly points to Woot's Tartarus: [crash-2021-02-16_13.50.27-server.txt](https://github.com/Ipsis/Woot/files/5991854/crash-2021-02-16_13.50.27-server.txt)

Happens when creating a new world or trying to log into an existing world (which had Woot 1.16.4-1.0.3.2 working for at least one server start). Might be a mod conflict, I will try to narrow this down when I have time, may take a bit as 44 mods have been updated since it last worked. :/

If I disable the Woot mod I have no issues starting or logging into my server or world.

**Comment by Ipsis** [comment] 2021-02-20 11:00
I had booted Woot with 1.16.5 and managed to generate the world fine, so assumed that everything was good., but clearly that is not the case. I'll have to see if there is something special for 1.16.5 for chunk generation that has changed.

[Retested I'm not getting the issue on 1.16.5-36.022 or with the new DireWolf20 pack]

(I've seen reports of some dimension issues when loading older worlds that were fixed in Forge 1.16.5, however I've not seen any crash logs matching up with those reported above).

Quick question - are these just client or are you running dedicated servers?

**Comment by cosmo5001** [comment] 2021-02-20 15:41
I have been getting this same error and I also believe it is a mod conflict because I updated a bunch of other mods and added some as well since it last worked and I have also downgraded to the 1.0.3.1 version and got the same error
1.0.3.2
[crash-2021-02-18_17.26.13-server.txt](https://github.com/Ipsis/Woot/files/6015365/crash-2021-02-18_17.26.13-server.txt)
1.0.3.1
[crash-2021-02-20_07.21.16-server.txt](https://github.com/Ipsis/Woot/files/6015366/crash-2021-02-20_07.21.16-server.txt)


Update: works after a few more updates
Mods updated:
Architectury API (Forge)
Cloth Config API (Forge)
CraftTweaker
Excavator Mod
FallingTree
FTB Ultimine
Lollipop
OreTweaker
Powah!
Spatial Harvesters [FORGE]
Vampirism - Become a vampire!

Edit:
Mods in common:
vampirism
ftb ultimine
Architectury

Edit 2: changelog for vampirism update:
- Fix crash with dimension mods
- Fix automatic blood value calculation
- Remove some of the stronger resistance potions
- Slightly nerf some other hunter potions
- Fix/adjust structure density for camps and villages

**Comment by cosmo5001** [comment] 2021-02-20 16:47
the problem is the vampirism mod and they have already published an update

**Closed as completed** 2021-02-21 10:26 UTC
Labels: 1.16.5
