### ISSUE TITLE
Auto-crafting consumes hammer, obsidian, and dye

### ISSUE THREAD

**Issue by Serifina** [Ipsis/Woot#170] opened 2017-03-29 19:04 UTC
Minecraft Ver: 1.10.2
Pack: FTB Beyond

When using Applied Energistics 2 autocrafting, the hammer, dye, and obsidian in the recipe (all meant to be returned) are consumed. This is likely because the recipes are coded to force them to drop into the player inventory when the crafting recipe is run.

Proper behavior, and fixing this, would probably be to have the recipe leave those items where they are in the crafting grid. The AE2 system would then pull them back in (and if a player is crafting manually, they can remove those items from the grid by hand).

**Comment by Ipsis** [comment] 2017-03-29 19:39
This one is fixed in the release I'm going to make soon (1.10.2-1.3.0).
To make it work with AE2 I've had to chance the recipe a bit so that it works in the vanilla way.
So basically instead of obsidian it will consume the much cheaper cobblestone.
Unfortunately there was no obvious way round that.

Hopefully the new release will be out this weekend.

**Comment by Ipsis** [comment] 2017-03-31 19:37
Duplicate of 138

**Closed by Ipsis** 2017-03-31 19:37 UTC
Labels: duplicate
