### ISSUE TITLE
Crash when WitherCrumbs is used alongside WOOT mod

### ISSUE THREAD

**Issue by Gunner76th** [Ipsis/Woot#140] opened 2017-02-22 05:19 UTC
[crash-2017-02-21_23.53.46-server.txt](https://github.com/Ipsis/Woot/files/792290/crash-2017-02-21_23.53.46-server.txt)

Cross posting this to Turkey2349/WitherCrumbs as well since the crash is related to both mods. I have removed WitherCrumbs to resolve the issue at present.

**Comment by Gunner76th** [comment] 2017-02-22 05:20
https://github.com/Turkey2349/WitherCrumbs/issues/7

**Comment by Ipsis** [comment] 2017-02-22 07:15
I'll load up Wither crumbs in Dev environment and see if so can track down the cause of the crash.

**Comment by Ipsis** [comment] 2017-02-25 14:22
Unfortunately I cannot replicate this crash.
Is there some configuration I need change in the withercrumbs.cfg?
I've tried ReplaceVanillaWithers=true but that didn't seem to cause the crash.

Does the crash only happen when you spawn a genuine WitherCrumbs wither?

I've also had a look at the WitherCrumbs code that I think is causing the crash, but nothing jumps out as wrong.

**Comment by Ipsis** [comment] 2017-02-25 14:53
So basically the crash is happening in the WitherCrumbs code in the EntityHumanWither.dropFewItems code. I don't understand why. Something is null in that code, possibly due to me using a FakePlayer, but I honestly dont know.

However looking at the way the mod works, I don't think that you would be able to farm the items from those WitherCrumbs Withers.

What you can do in the meantime is stop those entities from being used by the factory by using the blacklist.

In the Woot.cfg - globalPrismBlacklist add Woot:none:withercrumbs.Wither_Crumb

That should allow you to use WitherCrumbs but not allow Woot to spawn them, until Turkey2349  can tell me exactly what is causing the crash in his code and I can try and update Woot to satisfy that or internally blacklist the mod stop any future issues.

**Comment by Ipsis** [comment] 2017-03-25 13:05
Since this is now blacklisted internally in Woot and there is no input from The WitherCrumbs author as to what might be going on I'm going to close this.

**Closed by Ipsis** 2017-03-25 13:05 UTC
Labels: bug
