### ISSUE TITLE
Erebus compatiblity with Woot 1.12

### ISSUE THREAD

**Issue by vishalkotwar** [Ipsis/Woot#358] opened 2018-05-12 22:41 UTC
Hi, 
 Erebus allows for animating any block into a living bug (called animated block) through [wand of animation](http://the-erebus.wikia.com/wiki/Wand_of_Animation). In 1.7.10 through MFR's Autospawnner we were able to clone these bugs and get the block back. Which is not available option in 1.12 minecraft. (I guess is the hold up for PO3).
I tried the above with Woot factory/farm, putting the "animated block" - factory controller in place. in a tier 4 factory. The factory heart was accepting power but did not display any drop item/loot. 
![woot](https://user-images.githubusercontent.com/39226511/39962055-c21dc6c6-5661-11e8-991f-11ecb36d1956.jpg)
    Also while using enderio's powered spawnner there is a bug/error where it turns every "animated block bug(mob)" into the stone type "animated block bug(mob)". Which I guess is because they (mobs made with wand of animation) all are called "animated block" and drops only stone as loot. 

Now I come to my question : Is it possible to successfully get the drops/ loot of every different animated block mob? 
If so How can the configs/loot tables be edited for them to drop/generate the specific block in the woot factory/farm? Can I edit customdrop.config for it? I feel it can work but how can I differentiate between different animated block mob types?
If this is possible I hope we get 1 more step closer to PO3 release (without MFR).

P.S. I am new to github, modding, etc. do not get offended if I stepped out of my line to ask you to help me do something.

**Comment by Ipsis** [comment] 2018-05-13 09:38
I've got no problems with people asking for assistance with mod support etc.

Normal mobs are "unique" in that the internal minecraft name eg. minecraft:cow represents one type of mob. However for Erebus, the animated block mob actually represents a whole multitude of different mobs, each with internal data that says what the original block was.

When an Erebus mob dies, it then drops the original item based on the internal data.

So what will happen with Woot is that the mob that I track will be called something like "erebus:animated_block". Woot will then test spawn a few hundred of these mobs and learn their drops.
However the mob that Woot spawns, will be missing the extra information ie. the original block. This could well explain the lack of any drops.

Woot would have to not only work out the entity name that you captured using the shard, but then also store the original item/metadata that the mob had. It then also have to spawn the Erebus mob and use custom code to program the internal origin data correctly.

So unfortunately without me adding a lot of custom handling for Erebus, then Woot is not going to work with the mod. Woot is almost unique in the way that it handles mob farming, but does have its limitations. Other mob farming mods such as MFR work in a different way, which is why they can handle this situation.

It does sound like I will need to internally blacklist the Erebus mod as incompatible.
This will mean you wont be able to capture the mob in the first place.
I've done this for a few mods that are just not compatible.

**Comment by wamc2017** [comment] 2018-05-13 12:17
@vishalkotwar,
Industrial Foregoing (which is the spiritual successor to MFR) got this feature implemented, but it is disabled by default (the config option is enableExactCopy)
The problem is, spawning exact copys of mobs could be used to duplicate blocks/items, for instance if you capture a zombie holding a diamond and you spawn him with this option enabled, you get a lot of diamonds... (That's why most mods, which add spawners don't allow to spawn exact copys, which is not a bug, more a prevention to disallow duplication)

@Ipsis,

if you're going to blacklist the animated blocks, you should also disable the Umbergolem Idol Guardians, which also got their type (mud, gold, iron, jade) defined by metadata and if you capture one of them, you only get the default (mud) drops...

**Comment by Ipsis** [comment] 2018-05-13 12:45
I was originally going to blacklist all of Erebus but after loading the mod, there are other mobs which I was not aware of. That means I'll only blacklist specific mobs, not the complete mod.

@wamc2017 Thanks for highlighting the Umbergolem Idol Guardians.

**Comment by Ipsis** [comment] 2018-05-13 13:50
I've blacklisted the Animated Block, Umbergolem and the Antlion Overlord - which has some custom onDeath handling to spawn special drops which also wont work with Woot.

**Comment by Ipsis** [comment] 2018-05-13 13:52
79766bab74db55a3da9332429779d0679f51547c

**Comment by wamc2017** [comment] 2018-05-13 17:57
Hmm, wouldn't it be better if the drops which are normally spawned by the antilion overlords ondeath handling are added automatically to the custom_drops.json (like the drops from the ender/chaos dragon) instead of disabling him? Or does this ondeath handling break anything, when the overlord is not killed in the erebus dimension? 

I think the tarantula brood mother also got some similar mechanic as the antilion overlord after her death and she should be treated the same...

**Comment by Ipsis** [comment] 2018-05-13 19:17
It could be handled by custom_drops.json.
I'm not sure if the onDeathUpdate is actually called when Woot does the kill for learning.
I couldn't see anything bad in Tartarus from the deaths.

So I can look into handling both the tarantula and Antilion Overlord.
The question is should I?
As I don't use Erebus, am I ruining the mod by enabling this support for the bosses?
(I'm always worried about this, especially if it bypasses the work that the other mod author has put in)

I might have to clone the repository to search for anything else with onDeathUpdate, as Github wont let you search the code for anything but the current branch (eg 1.9).

**Comment by wamc2017** [comment] 2018-05-14 23:43
Hmm, have used Erebus several times and I think it would not be ruining the mod if the bosses could be spawned with woot, because fighting them is as repetitive as the wither or chaos guardian and the mobs don't drop anything different as before (they are not like the gaia guardian, which drops "ten thousand" different things)

But tbh that's only my opinion and I'm not the mod author, I think if I find some time tomorrow I will open an issue on their tracker, asking for their opinion if they should be able to be spawned (with enabled custom drops) or be disabled by default. :)

**Comment by vishalkotwar** [comment] 2018-05-18 07:06
Bummer. Thanks both of you.. close this as you wish to Ipsis

**Comment by Ipsis** [comment] 2018-05-18 19:11
I'm going to try and just add it to custom_drops.
If it works, I'll commit it and people can just blacklist the mob if they dont like it.

**Comment by Ipsis** [comment] 2018-05-18 19:47
![2018-05-18_20 36 38](https://user-images.githubusercontent.com/5602759/40254402-33010470-5adb-11e8-98be-f03cb7bf26e1.png)
![2018-05-18_20 47 08](https://user-images.githubusercontent.com/5602759/40254776-a6c37162-5adc-11e8-81d3-77354db71af8.png)

Antlion Boss - 100% droprate of 1 for - Antlion Egg, War Hammer, Soul Crystal.
Code seemed to indicate these were guaranteed.
Tarantula Mini Boss - 100% droprate of 1 for - Tarantula Egg, Tarantula Boss Trophye

I've got a more difficult bug that I'm thinking about - hence I fixed this one :)

[Note to me: update the changelog before closing this]

**Closed as completed** 2018-05-21 19:26 UTC
Labels: 1.12
