### ISSUE TITLE
Spelling/incorrect term used

### ISSUE THREAD

**Issue by Gunner76th** [Ipsis/Woot#171] opened 2017-03-31 04:08 UTC
For one of your items used in the WOOT mod, I wanted to let you know you are using the wrong term for one of the crafting items. The woot:dyes that are used to form certain parts for the crafting of WOOT blocks should be die. In machining a tool used to form something else is referred to as a die. The dye you have is used to identify a coloring agent used to dye something such as dandelion yellow.  I have provided links to help better explain the differences.

https://en.wikipedia.org/wiki/Die_(manufacturing)

https://en.wikipedia.org/wiki/Dye

**Comment by JaSpr** [comment] 2017-03-31 04:50
Duplicate of #156. Resolved in 76cec41

**Comment by Gunner76th** [comment] 2017-03-31 04:54
Copy that, also commented on that commit a suggestion.

**Closed** 2017-03-31 06:11 UTC
Labels: duplicate
