### ISSUE TITLE
Conatus Consumption increases

### ISSUE THREAD

**Issue by dBHI-zz** [Ipsis/Woot#497] opened 2021-02-04 16:00 UTC
Hello,

sometimes the consumption of the Conatus Fluid increases to more than double and goes back to normal after breaking and rebuilding the farm. The consumption in my T-4 Farm with Wither Skeletons, Zombies, Skeletons and Sheep for example is normaly at 476 with all perks and sometimes switches to 1036. Without my "Stoke the Boiler" Upgrades it is at 680. This problem occurs in all Woot Factories of mine simultaniously. I have not found out what causes the issue, I regularly check the farms and it happens every few hours. I already tried to force it by switching dimensions, but unsuccessfully. The Farms are always chunkloaded if that matters.

Before breaking:
![image](https://user-images.githubusercontent.com/3235171/106919211-374c1900-670a-11eb-80a1-279a44412a2b.png)

After rebuilding:
![image](https://user-images.githubusercontent.com/3235171/106919279-4af77f80-670a-11eb-99f2-88af82e3be70.png)

**Comment by Ipsis** [comment] 2021-02-06 11:51
The recipes are set when the factory is formed or you change an upgrade. From your example above the setup looks identical in each.
Can I just clarify - the factory runs correctly, but sometimes when you open the GUI the incorrect Conatus Fluid is incorrect?
Could you post your debug.log when this happens -- I log part of the recipe calculation to that which might show what the issue is.
It is completely possible that this is a visual only issue and the used recipe is correct - but I'm not sure about this yet.

**Comment by dBHI-zz** [comment] 2021-02-06 23:29
I will look out for the next time and send the debug output. I think it was not just a visual bug, as my Conatus production was not enough anymore for sustaining my factories. Without the bug the production was enough (at least if I was not mistaken). I have built a second production line to prevent the factories from stopping.

**Comment by Ipsis** [comment] 2021-02-07 11:11
I've setup the same tier of factory as you and with the same mobs. I'll leave it running and see if I get the same issue as a quick test. (Of course it might only happen with other mods present - but it is worth a try just now)

Quick question - you said you factories were chunk loaded - were any on a chunk boundary? (Shouldn't make any difference as your guis show the exact same factory setup so it is more out of interest than anything else)

**Comment by dBHI-zz** [comment] 2021-02-07 23:32
Hi, two of my Factories are on Chunk-Boundaries. But all of the chunks are loaded:
![2021-02-08 00_10_16-Window](https://user-images.githubusercontent.com/3235171/107162516-fb33e500-69a3-11eb-8082-4ed7c2a4af5e.jpg)
(I am looking to the top left on the minimap, so the chunks in the above picture is the one below me and the two on top of me in the minimap)
![2021-02-08 00_11_36-Window](https://user-images.githubusercontent.com/3235171/107162517-fd963f00-69a3-11eb-9a05-199db8716653.jpg)
The error occured again, so here is the debug log:
[debug.log.gz](https://github.com/Ipsis/Woot/files/5940379/debug.log.gz)
One of the factories (The one in the back) kept the correct consumption level (just chicken, squid, rats from rats mod, and bats) for about 200 Conatus Fluid per action. I broke and rebuild 2 of the defect ones about a minute before the end of the log.

**Comment by Ipsis** [comment] 2021-02-08 19:11
Thanks, that debug helped me see the calculations.
I found a zombie/witherskeleton/skeleton/sheep producing fluid cost of 1036 which is your error state.
Later on there is the same but fluidcost of 476. 


```
Broken
Zombie fluid 200/PERK 30.0/saves 60/140
Wither Skeleton fluid 1000/PERK 30.0/saves 300/700
Skeleton fluid 200/PERK 30.0/saves 60/140
Sheep fluid 80/PERK 30.0/saves 24/56
Cost 1036
Base 320. 476
actual 320
```


```
Correct
Zombie fluid 200/PERK 30.0/saves 60/140
Wither Skeleton fluid 200/PERK 30.0/saves 60/140
Skeleton fluid 200/PERK 30.0/saves 60/140
Sheep fluid 80/PERK 30.0/saves 24/56
Cost 476
Base 320 ticks, actual 320
```

So the Wither Skeleton base fluid cost in the broken one is 1000 and in the correct one is 200.

I haven't worked out why yet, but at least I can see what is going wrong.

**Comment by Ipsis** [comment] 2021-02-13 13:42
So the "good" news is that I can see the exact same thing. When I start the game, the Wither Skeleton is 1000 cost, then I break/build and it is down to 200.

On first run - 100 health points * 10 fluid per health = 1000
Reform - 20 health points * 10 fluid per health = 200 

So I think I found the problem. Caching the health value of the mob was still causing it to use the unknown value of 100. The reform then correctly used the cache value. Literally a function was returning false on success instead of true.

That should fix the issue and will be in the next release. (1.16.4-1.0.3.2)

**Closed as completed** 2021-02-13 13:42 UTC
Labels: bug, 1.16
