### ISSUE TITLE
WOOT 1.15.2 FLUID VAT BUG REPORT- ATM5

### ISSUE THREAD

**Issue by SakiSkai** [Ipsis/Woot#431] opened 2020-06-11 14:55 UTC
Liquid inventories are empty and machine does not accept water via pipes.

Video explanation below
https://www.twitch.tv/videos/647776497

**Comment by Ipsis** [comment] 2020-06-11 17:14
Just tried standalone with ATM5 and I can the same issue.
The same issue doesn't occur with the mod by itself.

It looks it is visual only - since the debug shows me that the VAT output tank has liquid contents.

So I have the Mekanism tank with water connected via a Mekanism pipe putting water into the VAT from the left.
Then I have a Mekanism pipe connecting the VAT to a tank.
The tank is then filling up with fluid from the VAT.

So there is something in the ATM5 pack that doesn't like my gui, or is highlighting a problem with it.

**Comment by Ipsis** [comment] 2020-06-14 12:50
Found what I believe to be the issue
`[13:43:17] [Server thread/ERROR]: Unable to locate field listeners (listeners) on type net.minecraft.inventory.container.Container
net.minecraftforge.fml.common.ObfuscationReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: listeners
	at net.minecraftforge.fml.common.ObfuscationReflectionHelper.findField(ObfuscationReflectionHelper.java:242) ~[?:?]
	at net.minecraftforge.fml.common.ObfuscationReflectionHelper.getPrivateValue(ObfuscationReflectionHelper.java:87) [?:?]
	at ipsis.woot.modules.fluidconvertor.blocks.FluidConvertorContainer.func_75142_b(FluidConvertorContainer.java:112) [?:1.15.2-1.1.0.0]
	at net.minecraft.entity.player.ServerPlayerEntity.func_70071_h_(ServerPlayerEntity.java:317) [?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:600) [?:?]
	at net.minecraft.world.server.ServerWorld$$Lambda$19166/480176016.accept(Unknown Source) [?:?]
	at net.minecraft.world.World.func_217390_a(World.java:536) [?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:401) [?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849) [?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114) [?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NoSuchFieldException: listeners
	at java.lang.Class.getDeclaredField(Class.java:2070) ~[?:1.8.0_51]
	at net.minecraftforge.fml.common.ObfuscationReflectionHelper.findField(ObfuscationReflectionHelper.java:236) ~[?:?]`

So these errors only occur when running outside the Intellij IDE so clearly I'm doing something wrong with reflection.

**Comment by Ipsis** [comment] 2020-06-14 13:14
Updated the code to not use obfuscation and just use an access transfer to access the listeners,

**Comment by SakiSkai** [comment] 2020-06-14 13:18
Thanks for the quick response, your mod is fricking neat

**Comment by Ipsis** [comment] 2020-06-14 14:31
Fixed in 1.15.2-1.1.0.1 which is awaiting approval on CurseForge.

**Closed as completed by Ipsis** 2020-06-14 14:31 UTC
Labels: 1.15, compat
