### ISSUE TITLE
Crashing with Bloodmagic 3.1.3-18 and newer

### ISSUE THREAD

**Issue by thakyZ** [Ipsis/Woot#550] opened 2021-10-05 00:08 UTC
When using bloodmagic and woot together the server crashes.
This is a issue for the pull request I am about to make
https://gist.github.com/thakyZ/1a49b94e93fbd76b91a6c9ca69edce3d

**Comment by kittycat2002** [comment] 2021-10-05 00:16
To further build on this issue, the crash occurs when you activate the blood magic ritual.

**Comment by kittycat2002** [comment] 2021-10-05 00:17
also see https://github.com/WayofTime/BloodMagic/commit/35d00d697bacb67e1295d8d6f70510c2d99cdef2#diff-8a5a64f90b0c582eca09f914299898cbee2a6289d9609a3cb1a452a352c33022 for the cause of the issue.

**Comment by Brillik** [comment] 2021-11-14 20:49
Has there been any development on this issue? I'm playing Ragnamod VI (Beta 6.0.24) with Blood Magic 3.1.5-25 and Woot 1.0.8.0, and have unfortunately put my server into a crashing loop twice trying to make this work. I've got a tier 5 woot altar, and a tier 5 blood altar. For testing, I was using a sheep controller, and the flayed perk. The both altars were stopped and not doing anything when I tried to activate the ritual with 100k LP in my personal system. If anyone has advice, or a fix, I'd love to hear it. Thanks for your time and for a great mod!

**Comment by thakyZ** [comment] 2021-11-14 23:28
@Brillik if you are playing singleplayer all I can say is to build Woot from my pull request: #551

**Comment by Ipsis** [comment] 2022-01-01 11:06
I've pulled in @thakyZ  (thanks again) fix for this crash and uploaded Woot 1.0.8.1 to CurseForge - so hopefully this is all fixed up now.

(I have very little time to spend on Woot at the moment hence the very slow turnaround with this issue)

**Closed as completed by Ipsis** 2022-01-01 11:06 UTC
